#!/bin/sh
# This file can be sourced in your init

# This layout doesn't have a name because it's used in others
read -r -d '' HORIZONTAL << EOM
(
  ( hor:
    ver
    (( ver: full deck ) 1 0.5)
  ) 1 0.62
)
EOM

read -r -d '' TRIPLE << EOM
(
  ( hor:
  	hor
    deck
  ) 2 0.65
)
EOM

# An example for conditional layouts
read -r -d '' MOSAIC << EOM
mosaic
(
  (3 > ( v:
  	$HORIZONTAL
    ((h: f d) 1 0.62)
  ) ? ((v: h h) 1)) 3 0.6
)
EOM

read -r -d '' STACK << EOM
stack
(
  ( v:
    $TRIPLE
    $TRIPLE ) 1 0.57
)
EOM

read -r -d '' CENTERED << EOM
centered
(
  ( v:
  	$TRIPLE
    (( h: f d ) 1 0.63)
  	$TRIPLE
  ) 1 0.47 1
)
EOM

# Inspired by Stacktile - https://git.sr.ht/~leon_plickat/stacktile
read -r -d '' STACKTILE << EOM
stacktile
( ver:
  (( h: full deck ) 1 0.62)
  (( h: full deck ) 1 0.62)
)
EOM
