#!/bin/sh

# Nested layouts (examples)
# Source this file in yout init

# Looks like the ordinary master and stack layout when main_count is one
# but when increased, the additional windows in the main area will be aligned
# below the main window.
read -r -d '' STACK << EOM
(
  {
    vertical:
    (
      {horizontal: full, vertical};
      1;0.65;0
    ),
    horizontal
  };
  1;0.65;0
)
EOM

# Like STACK except the main and slave areas are inverted
read -r -d '' RSTACK << EOM
(
  {
    vertical:
    horizontal,
    (
      {horizontal: full, vertical};
      1;0.68;0
    )
  };
  1;0.65;1
)
EOM

# Splits the output area vertically in 2 areas.
# The main area has a count of one and a horizontal layout.
# Below the the top window in the slave area windows are stacked on
# top of each others like a deck of cards.
read -r -d '' DECK << EOM
(
  {
    vertical:
    horizontal,
    (
      {horizontal: full, deck};
      1;0.65;0
    )
  };
  1;0.65;0
)
EOM

# Like DECK except the main and slave areas are inverted
read -r -d '' RDECK << EOM
(
  {
    vertical:
    (
      {horizontal: full, deck};
      1;0.65;0
    ),
    horizontal
  };
  1;0.65;1
)
EOM
